### ISSUE TITLE
Pulling content onto pages (via "Add item") not working

### ISSUE THREAD

**Issue by cmiller02** [risd/risd-congratulations-v2#2]
@rubillionaire 
When you have a moment, would you mind looking into why I can't currently add a Universal - Pages item here. (I tried the "Rebuild Search Index.")

![Screen Shot 2019-11-14 at 3 13 00 PM](https://user-images.githubusercontent.com/14020234/68975517-7ae2fc00-07c1-11ea-83e3-36397968692f.png)

Actually, at a quick glance, I don't think that "Add item" is working anywhere in the CMS.

**Comment by rubillionaire** [comment]
all of these relationship widgets that connect different content types are driven by the CMS search functionality. it looks like that was not working due to an incorrect URL for the search server. it was looking for an `http` server, since the CMS is served under `https`, it blocks any `http` calls that are made in the browser. this is a security feature of many browsers. i updated the search server URL and all relationship widgets appear to be working.
