### ISSUE TITLE
Changing button text on modal

### ISSUE THREAD

**Issue by cmiller02** [risd/risd-congratulations-v2#21]
@rubillionaire can you please change the modal buttons to be:
on the left: “ACCESS THE PORTAL” and on the right: “CONTINUE TO THIS SITE”

as opposed to what they are currently:
<img width="1090" alt="Screen Shot 2020-12-10 at 3 04 43 PM" src="https://user-images.githubusercontent.com/14020234/101823651-18aa1700-3af9-11eb-8f3c-6304e0e8cf79.png">

And WHERE these buttons go will just stay the same. Thanks so much!

**Comment by rubillionaire** [comment]
@cmiller02 i have updated the buttons to carry their new text. doing so displayed some limitations with our current styles. they didn't carry the longer strings of text very well.

the first thing i noticed is that text is going to want to render on 2 lines if it wants to live within the shapes. this looks really strange with the way the text on the second line hits the edge of the button

![Screen Shot 2020-12-14 at 3 03 49 PM](https://user-images.githubusercontent.com/434737/102132077-20cbc480-3e21-11eb-81dd-2d15e79b8d3c.png)

so i went ahead and centered the text and added a little padding so that it could have its space back. but then black buttons look overly tight within the shapes they barely sit within.

![Screen Shot 2020-12-14 at 3 13 37 PM](https://user-images.githubusercontent.com/434737/102132302-72744f00-3e21-11eb-8e42-31c8987a5c21.png)

so i tried bringing the button text size down to 80% of its original size, and now the boxes have a bit more space in their shapes.

![Screen Shot 2020-12-14 at 3 13 44 PM](https://user-images.githubusercontent.com/434737/102132507-b5362700-3e21-11eb-92b5-e93609e53d2a.png)

that is what is up now at our staging site, https://welcome-ph2.risd.systems/

let me know what you think about this solution

**Comment by cmiller02** [comment]
thank you so much for tinkering with all this @rubillionaire !

Wanted to pull @room421 in here, as this came from him...

**Comment by room421** [comment]
@rubillionaire could you delete the "the" in the portal one? And change the other to "ENTER THIS SITE"?

**Comment by rubillionaire** [comment]
@cmiller02 @room421 ohh good call, that looks like it fits much better with our original styles:

https://welcome-ph2.risd.systems/

![Screen Shot 2020-12-15 at 1 20 09 PM](https://user-images.githubusercontent.com/434737/102255626-51226a00-3ed8-11eb-9110-f59c4f7deee0.png)

**Comment by cmiller02** [comment]
oow I like this! @room421 are you good with what @rubillionaire has above?

**Comment by room421** [comment]
Looks great! Thanks again.

@cmiller02 can you tell Hattie when it's live?

**Comment by rubillionaire** [comment]
@room421 thanks for taking a look!

@cmiller02 i went ahead and deployed, its now live on https://welcome.risd.edu/

**Comment by cmiller02** [comment]
great! I see it live, so will now tell Hattie @room421 . Thanks so much @rubillionaire ! Closing this now!
